spring:
  datasource:
    url: jdbc:mysql://mysql-docker:3306/serverdb
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    oracleucp:
      network-protocol: springmysql-net
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: create

