spring:
  datasource:
    password: 123456789
    url: jdbc:mysql://127.0.0.1:3305/serverdb
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
      hibernate:
        ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

