spring:
  datasource:
    url: jdbc:mysql://mysql-docker:3306/serverdb
    password: 123456789
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
      hibernate:
        ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

